name: Terraform CI/CD Pipeline

on:
  push:
    branches: [ "terraform-deployment" ]

permissions:
  contents: read

jobs:
  terraform:
    name: "terraform-job"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false

    - name: Terraform Output
      run: |
        echo TEST=$(terraform output -raw private_key) >> $GITHUB_ENV
        echo TEST1=$(terraform output instance_public_ip)
        echo TEST2=$(terraform output instance_id)
        echo TEST3=$(terraform output instance_dns)

  build:
    name: "build the application"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Build
        run: ./gradlew build
      - name: Copy jar file to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: esop-trading-1.0
          path: build/libs/esop-0.1-all.jar

  deploy:
    name: "deploy the application"
    runs-on: ubuntu-latest
    needs: 
      - terraform
      - build
    steps:
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Download jar file
        uses: actions/download-artifact@v3
        with:
          name: esop-trading-1.0
      - name: Copy jar file to ec2 instance
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KAJAL_EC2_SSH_KEY }}
          SSH_HOST: ${{ secrets.KAJAL_SSH_HOST }}
        run: |
            eval `ssh-agent`
            echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
            scp -o StrictHostKeyChecking=no "esop-0.1-all.jar" ec2-user@$SSH_HOST:~
            ssh -o StrictHostKeyChecking=no ec2-user@$SSH_HOST -t "java -jar esop-0.1-all.jar"
      
