name: CI/CD Pipeline
on:
  push:
    branches: [ deploy-trading ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - uses: actions/checkout@v2
      # Step 2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      # Step 3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle test
        run: ./gradlew test

      - name: Execute Gradle build
        run: ./gradlew shadowJar

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: build/libs/esop-0.1-all.jar
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: deploy to server
        uses: kajalp238/esop-trading@deploy-trading
        env:
          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${ { secrets.HOST_DNS }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          TARGET: ${ { secrets.TARGET_DIR }}
