name: CI/CD Pipeline
on:
  push:
    branches: [ deploy-trading ]

jobs:


  continuous-deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deploy-trading'
    steps:
      - name: Execute Gradle build
        run: ./gradlew shadowJar
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: build
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${ { secrets.HOST_DNS }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          TARGET: ${ { secrets.TARGET_DIR }}
