name: Terraform CI/CD Pipeline

on:
  push:
    branches: [ "terraform-deployment" ]

permissions:
  contents: read

jobs:
  terraform:
    name: "terraform-job"
    outputs:
      key: ${{ steps.terraform_output.outputs.key }}
      host: ${{ steps.terraform_output.outputs.public_ip }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform Init
      run: terraform init

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false

    - name: Terraform Output
      id: terraform_output
      run: |
        echo key=$(terraform output -raw private_key) >> $GITHUB_OUTPUT
        echo public_ip=$(terraform output instance_public_ip) >> $GITHUB_OUTPUT
        echo ${{env.key}}

  build:
    name: "build the application"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Build
        run: 
          ./gradlew build
      - name: Copy jar file to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: esop-trading-1.0
          path: build/libs/esop-0.1-all.jar

  deploy:
    name: "deploy the application"
    runs-on: ubuntu-latest
    needs: 
      - terraform
      - build
    steps:
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Download jar file
        uses: actions/download-artifact@v3
        with:
          name: esop-trading-1.0
      - name: Copy jar file to ec2 instance
        env:
          SSH_PRIVATE_KEY: ${{needs.terraform.outputs.key}}
          SSH_HOST: ${{ needs.terraform.outputs.private_ip }}
        run: |
            echo SSH_PRIVATE_KEY
            eval `ssh-agent`
            echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
            scp -o StrictHostKeyChecking=no "esop-0.1-all.jar" ec2-user@$SSH_HOST:~
            ssh -o StrictHostKeyChecking=no ec2-user@$SSH_HOST -t "java -jar esop-0.1-all.jar"
      
